NiklasEi/bevy_asset_loader

bevy_asset_loader/examples/two_collections.rs
bevy_asset_loader/src/lib.rs
bevy_asset_loader/tests/can_run_without_next_state.rs
bevy_asset_loader/tests/ui/folder_and_path.rs
bevy_asset_loader/tests/ui/folder_and_path.stderr
bevy_asset_loader_derive/src/assets.rs
bevy_asset_loader_derive/src/lib.rs

Support for loading folders

---

CHANGELOG.md
README.md
bevy_asset_loader/src/asset_loader.rs

Make file endings for dynamic asset collections configurable

---

CHANGELOG.md
bevy_asset_loader/Cargo.toml
bevy_asset_loader/src/asset_collection.rs
bevy_asset_loader/src/asset_loader.rs
bevy_asset_loader/src/asset_loader/dynamic_asset.rs
bevy_asset_loader/src/asset_loader/dynamic_asset_systems.rs
bevy_asset_loader/src/lib.rs
bevy_asset_loader_derive/src/lib.rs

Correctly document items behind features and fix most doc links

---

CHANGELOG.md
README.md
bevy_asset_loader/Cargo.toml
bevy_asset_loader/assets/my.assets
bevy_asset_loader/examples/full_collection.rs
bevy_asset_loader/examples/full_dynamic_collection.rs
bevy_asset_loader/examples/two_collections.rs
bevy_asset_loader/src/asset_loader.rs
bevy_asset_loader/src/asset_loader/dynamic_asset.rs
bevy_asset_loader/src/asset_loader/dynamic_asset_systems.rs
bevy_asset_loader/src/asset_loader/systems.rs
bevy_asset_loader/tests/ui_with_2d_3d_features/key_and_any_other_attribute.rs
bevy_asset_loader_derive/src/assets.rs
bevy_asset_loader_derive/src/lib.rs

Load lists of files

---

bevy_asset_loader/Cargo.toml

Bump iyes_loopless version to v0.6.1

iyes_loopless v0.6.1

---

bevy_asset_loader/src/loading_state.rs
bevy_asset_loader/src/loading_state/dynamic_asset_systems.rs
bevy_asset_loader/src/loading_state/stageless/dynamic_asset_systems.rs
bevy_asset_loader/src/loading_state/stageless/systems.rs
bevy_asset_loader/src/loading_state/systems.rs
bevy_asset_loader/tests/continues_without_collection.rs
bevy_asset_loader/tests/stageless.rs
bevy_asset_loader/tests/stageless/can_run_without_next_state.rs
bevy_asset_loader/tests/stageless/continues_without_collection.rs
bevy_asset_loader/tests/stageless/init_resource.rs
bevy_asset_loader/tests/stageless/multiple_asset_collections.rs
bevy_asset_loader/tests/stageless/multiple_loading_states.rs

Continue to next state without collections

---

README.md

Add a note about configuring loading states in different places

---

CHANGELOG.md
bevy_asset_loader/Cargo.toml
bevy_asset_loader/src/loading_state.rs

Tested by running 'cargo test' and running examples "two_collections", "stageless_full_dynamic_collection", "atlas_from_grid" and "standard_material" successfully.

bump iyes deps

---

CHANGELOG.md
bevy_asset_loader/src/loading_state.rs
bevy_asset_loader/src/loading_state/dynamic_asset_systems.rs
bevy_asset_loader/src/loading_state/stageless/dynamic_asset_systems.rs

Correctly handle multiple calls to with_dynamic_collections

---

CHANGELOG.md
bevy_asset_loader/examples/full_collection.rs
bevy_asset_loader_derive/src/assets.rs

Stop stripping the folder name from paths in mapped folder collections

---

bevy_asset_loader/examples/full_collection.rs

Compare paths instead of strings in full_collection example

---

bevy_asset_loader/Cargo.toml

Remove features for optional dependencies and bump bevy_common_assets

---

bevy_asset_loader/src/loading_state.rs
bevy_asset_loader/src/loading_state/dynamic_asset_systems.rs
bevy_asset_loader/src/loading_state/systems.rs
bevy_asset_loader/tests/multiple_states.rs

Allow usage in multiple states

---

README.md
bevy_asset_loader/examples/atlas_from_grid.rs
bevy_asset_loader/examples/init_resource.rs
bevy_asset_loader/examples/progress_tracking.rs
bevy_asset_loader/examples/standard_material.rs
bevy_asset_loader/examples/two_collections.rs

And adapt examples
Resolves #128

Mention adding the default plugins before configuring a loading state

---

CHANGELOG.md
bevy_asset_loader/src/dynamic_asset.rs
bevy_asset_loader/src/loading_state.rs
bevy_asset_loader/src/loading_state/dynamic_asset_systems.rs
bevy_asset_loader/tests/reload_dynamic_asset_files.rs

Allow reloading of dynamic asset files

---

CHANGELOG.md
bevy_asset_loader/Cargo.toml
bevy_asset_loader/examples/full_collection.rs
bevy_asset_loader/examples/full_dynamic_collection.rs
bevy_asset_loader/src/lib.rs
bevy_asset_loader/tests/mapped_path_use_slash.rs
bevy_asset_loader_derive/src/assets.rs

Use slash in keys for mapped collections

---

bevy_asset_loader/examples/custom_dynamic_assets.rs
bevy_asset_loader/src/dynamic_asset.rs
bevy_asset_loader/src/loading_state.rs

Add systems to handle dynamic asset collections separately from addg the files themselves

---

bevy_asset_loader/src/loading_state/systems.rs
bevy_asset_loader_derive/Cargo.toml
bevy_asset_loader_derive/src/lib.rs

Update to syn v2

---

bevy_asset_loader/src/standard_dynamic_asset.rs

Deny unknown fields in standard dynamic assets

---

CHANGELOG.md
Cargo.toml
bevy_asset_loader/Cargo.toml
bevy_asset_loader/assets/full_dynamic_collection.assets.ron
bevy_asset_loader/examples/atlas_from_grid.rs
bevy_asset_loader/examples/full_collection.rs
bevy_asset_loader/examples/full_dynamic_collection.rs
bevy_asset_loader/src/standard_dynamic_asset.rs
bevy_asset_loader_derive/Cargo.toml
bevy_asset_loader_derive/src/assets.rs

Support configuring the image sampler for texture atlases

---

.github/workflows/ci.yml
CHANGELOG.md
bevy_asset_loader/Cargo.toml
bevy_asset_loader/src/standard_dynamic_asset.rs

Fix compilation without 2d 3d features

---

CHANGELOG.md
bevy_asset_loader/src/standard_dynamic_asset.rs

Add Serialize derive to standard dynamic assets

---

bevy_asset_loader/Cargo.toml
bevy_asset_loader/src/standard_dynamic_asset.rs

Fix and test serialization of StandardDynamicAssets
resolves #184 
Cc @feelingsonice

Fix serialization of StandardDynamicAsset

---

bevy_asset_loader/src/loading_state.rs
bevy_asset_loader/src/loading_state/dynamic_asset_systems.rs
bevy_asset_loader/src/loading_state/systems.rs
bevy_asset_loader/tests/multiple_loading_states.rs
bevy_asset_loader/tests/same_collection_multiple_times.rs

Don't get stuck with duplicate asset collections

---

.github/workflows/ci.yml

Split progress tracking CI job

---

bevy_asset_loader/tests/can_run_without_next_state.rs
bevy_asset_loader/tests/continues_to_failure_state.rs
bevy_asset_loader/tests/continues_without_collection.rs
bevy_asset_loader/tests/init_resource.rs
bevy_asset_loader/tests/mapped_path_use_slash.rs
bevy_asset_loader/tests/multiple_asset_collections.rs
bevy_asset_loader/tests/multiple_states.rs
bevy_asset_loader/tests/reload_dynamic_asset_files.rs

Enable more integration tests to run with all tested feature combinations

---

CHANGELOG.md
bevy_asset_loader/src/asset_collection.rs
bevy_asset_loader/tests/ui/missing_impl.rs
bevy_asset_loader/tests/ui/missing_impl.stderr

Add on_unimplemented diagnostics to AssetCollection trait

---

README.md
bevy_asset_loader/examples/no_loading_state.rs
bevy_asset_loader/src/asset_collection.rs

Document that the image annotation requires a loading state
